version: 2.1

jobs:
  build-and-push:
    docker:
      - image: cimg/base:stable
    steps:
      - setup_remote_docker:
          version: 20.10.18
      - checkout

      # Login to DockerHub
      - run:
          name: Docker Login
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin

      # Build Docker image
      - run:
          name: Build Docker Image
          command: docker build -t $DOCKERHUB_USER/video2gif:latest .

      # Push Docker image
      - run:
          name: Push Docker Image
          command: docker push $DOCKERHUB_USER/video2gif:latest

  run-docker-image:
    docker:
      - image: cimg/base:stable
    steps:
      - setup_remote_docker:
          version: 20.10.18

      # Login to DockerHub
      - run:
          name: Docker Login
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin

      # Pull image
      - run:
          name: Pull Docker Image
          command: docker pull $DOCKERHUB_USER/video2gif:latest

      # Run container
      - run:
          name: Run Docker Container
          command: |
            docker run -d -p 8000:8000 \
              --name fastapi-container \
              $DOCKERHUB_USER/video2gif:latest

      # Test API endpoint
      - run:
          name: Test API
          command: |
            sleep 5  # wait for container to start
            curl --fail http://localhost:8000/docs

workflows:
  build-test-deploy:
    jobs:
      - build-and-push
      - run-docker-image:
          requires:
            - build-and-push
