version: 2.1

jobs:
  run-docker-image:
    docker:
      - image: cimg/base:stable
    steps:
      # Enable Docker-in-Docker so we can run docker commands
      - setup_remote_docker:
          version: default

      # Login to DockerHub (skip if your image is public)
      - run:
          name: Docker Login
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin

      # Pull image
      - run:
          name: Pull Docker Image
          command: docker pull $DOCKERHUB_USER/video2gif-gpu:v0

      # Run container
      - run:
          name: Run Docker Container
          command: |
            docker run -d -p 8000:8000 \
              --name fastapi-container \
              $DOCKERHUB_USER/video2gif-gpu:v0

      # Test API endpoint
      - run:
          name: Test API
          command: |
            sleep 5  # give container time to start
            curl --fail http://localhost:8000/docs

workflows:
  run-workflow:
    jobs:
      - run-docker-image
